# Generated by Django 3.0.3 on 2020-02-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='tetle',
            new_name='title',
        ),
    ]
